# Generated by Django 4.2.6 on 2024-04-10 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoucherPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='static/images/')),
            ],
        ),
        migrations.RenameModel(
            old_name='Photo',
            new_name='GalleryPhoto',
        ),
    ]
