# Generated by Django 5.0.4 on 2024-09-02 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0002_alter_reservation_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlreadyMadeReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_surname', models.CharField(max_length=150)),
                ('email', models.EmailField(blank=True, default=None, max_length=254, null=True)),
                ('phone_number', models.CharField(blank=True, default=None, max_length=20, null=True)),
            ],
        ),
    ]
