# Generated by Django 5.0.4 on 2024-08-18 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0003_turnedoffday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turnedoffday',
            name='time_from',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='turnedoffday',
            name='time_to',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
