# Generated by Django 5.0.4 on 2024-09-02 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0003_alreadymadereservation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alreadymadereservation',
            name='name_surname',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
