# Generated by Django 5.0.4 on 2025-10-23 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0005_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='massage_name',
            field=models.CharField(blank=True, default='Masáž', max_length=250, null=True),
        ),
    ]
