# Generated by Django 5.0.4 on 2026-04-11 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0006_reservation_massage_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryphoto',
            name='photo',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='voucherphoto',
            name='photo',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
