# Generated by Django 5.0.4 on 2026-07-18 10:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0007_alter_galleryphoto_photo_alter_voucherphoto_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alreadymadereservation',
            options={'ordering': ('name_surname',), 'verbose_name': 'Uložená osoba', 'verbose_name_plural': 'Uložené osoby'},
        ),
        migrations.AlterModelOptions(
            name='galleryphoto',
            options={'verbose_name': 'Fotka galérie', 'verbose_name_plural': 'Fotky galérie'},
        ),
        migrations.AlterModelOptions(
            name='reservation',
            options={'ordering': ('-datetime_from',), 'verbose_name': 'Rezervácia', 'verbose_name_plural': 'Rezervácie'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ('-created_at',), 'verbose_name': 'Hodnotenie', 'verbose_name_plural': 'Hodnotenia'},
        ),
        migrations.AlterModelOptions(
            name='turnedoffday',
            options={'ordering': ('-date',), 'verbose_name': 'Deň voľna / obmedzenie', 'verbose_name_plural': 'Dni voľna / obmedzenia'},
        ),
        migrations.AlterModelOptions(
            name='voucherphoto',
            options={'verbose_name': 'Poukážka', 'verbose_name_plural': 'Poukážky'},
        ),
        migrations.AlterField(
            model_name='reservation',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='review',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
