# Generated by Django 5.0.4 on 2026-04-27 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0007_alter_galleryphoto_photo_alter_voucherphoto_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentQRCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('beneficiary_name', models.CharField(max_length=150)),
                ('iban', models.CharField(max_length=34)),
                ('swift', models.CharField(blank=True, max_length=11)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('currency', models.CharField(default='EUR', max_length=3)),
                ('variable_symbol', models.CharField(blank=True, max_length=10)),
                ('constant_symbol', models.CharField(blank=True, max_length=4)),
                ('specific_symbol', models.CharField(blank=True, max_length=10)),
                ('payment_note', models.CharField(blank=True, max_length=140)),
                ('beneficiary_address_1', models.CharField(blank=True, max_length=70)),
                ('beneficiary_address_2', models.CharField(blank=True, max_length=70)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Payment QR code',
                'verbose_name_plural': 'Payment QR codes',
                'ordering': ('title',),
            },
        ),
    ]
