# Generated by Django 5.0.4 on 2026-04-27 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='PaymentQRCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Interný názov v administrácii, napríklad Permanentka, Darčeková poukážka alebo Záloha.', max_length=120, verbose_name='Názov QR kódu')),
                ('beneficiary_name', models.CharField(help_text='Tento názov sa zobrazí pri platbe. Odporúča sa uviesť obchodné meno alebo meno účtu.', max_length=150, verbose_name='Meno príjemcu alebo firmy')),
                ('iban', models.CharField(help_text='Povinné pole. Zadajte IBAN účtu, na ktorý má zákazník zaplatiť.', max_length=34, verbose_name='IBAN')),
                ('swift', models.CharField(blank=True, help_text='Odporúčané hlavne pri zahraničných účtoch alebo ak to vyžaduje vaša banka.', max_length=11, verbose_name='SWIFT / BIC')),
                ('amount', models.DecimalField(decimal_places=2, default=0, help_text='Povinné pole. Suma, ktorá sa predvyplní po naskenovaní QR kódu.', max_digits=10, verbose_name='Suma')),
                ('currency', models.CharField(default='EUR', help_text='Bežne nechajte EUR.', max_length=3, verbose_name='Mena')),
                ('variable_symbol', models.CharField(blank=True, help_text='Odporúčané pri párovaní platieb. Ak ho nepoužívate, nechajte prázdne.', max_length=10, verbose_name='Variabilný symbol')),
                ('constant_symbol', models.CharField(blank=True, help_text='Vyplňte len vtedy, ak ho reálne používate.', max_length=4, verbose_name='Konštantný symbol')),
                ('specific_symbol', models.CharField(blank=True, help_text='Nepovinné pole pre doplnkové párovanie platieb.', max_length=10, verbose_name='Špecifický symbol')),
                ('payment_note', models.CharField(blank=True, help_text='Odporúčané. Napríklad Permanentka, Poukážka alebo názov služby.', max_length=140, verbose_name='Poznámka k platbe')),
                ('beneficiary_address_1', models.CharField(blank=True, help_text='Nepovinné. Môžete uviesť ulicu a číslo.', max_length=70, verbose_name='Adresa príjemcu - riadok 1')),
                ('beneficiary_address_2', models.CharField(blank=True, help_text='Nepovinné. Môžete uviesť PSČ a mesto.', max_length=70, verbose_name='Adresa príjemcu - riadok 2')),
                ('due_date', models.DateField(blank=True, help_text='Nepovinné. Vyplňte len ak chcete zákazníkovi predvyplniť splatnosť.', null=True, verbose_name='Dátum splatnosti')),
                ('is_active', models.BooleanField(default=True, help_text='Ak pole odškrtnete, záznam zostane uložený, ale budete ho vedieť odlíšiť ako neaktívny.', verbose_name='Aktívny')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Vytvorené')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Naposledy upravené')),
            ],
            options={
                'verbose_name': 'Platobný QR kód',
                'verbose_name_plural': 'Platobné QR kódy',
                'ordering': ('title',),
            },
        ),
    ]
